### ISSUE TITLE
建议增加几个小功能功能

### ISSUE THREAD

**Issue by Liyuk** [WittBulter/easyFindNumber#3]
1、有些磁力链接太长了，复制的时候部分内容在会出现拖动条，不方便复制粘贴，建议增加一键复制这样的功能，比如zclip；

2、其实可以加一个在线磁力链接解析器，毕竟迅雷解析太慢了

**Comment by WittBulter** [comment]
复制我来加上
解析器这个我先看看,后面一个版本来试试
谢谢
