### ISSUE TITLE
安装成功，但是搜索不到资源 =@@=

### ISSUE THREAD

**Issue by Bogon** [WittBulter/easyFindNumber#5]
<img width="1235" alt="2016-04-13 11 24 47" src="https://cloud.githubusercontent.com/assets/6748372/14481977/5f9bf214-016a-11e6-98bf-8e2b5f35b2e2.png">

**Comment by WittBulter** [comment]
我试了一下,是可以的.
你控制台有报什么错吗

**Comment by Bogon** [comment]
<img width="754" alt="2016-04-13 3 42 27" src="https://cloud.githubusercontent.com/assets/6748372/14486230/5e4ae7b6-018e-11e6-9356-68e01019450f.png">
没有报错，但是资源一直也是没有，抓包也没看到有请求发生？好奇怪呀，是我配置的不对吗，还是hosts文件需要配置？

**Comment by WittBulter** [comment]
不是这个原因.
打开页面的时候按F12,点搜索的时候看看Network项有没有请求.console有没有错误,试试其他的关键词.

**Comment by Bogon** [comment]
<img width="1227" alt="2016-04-13 3 55 47" src="https://cloud.githubusercontent.com/assets/6748372/14486576/433b1a5c-0190-11e6-9ef1-84c333304671.png">


<img width="1227" alt="2016-04-13 3 55 47" src="https://cloud.githubusercontent.com/assets/6748372/14486613/713b7514-0190-11e6-86e1-06453880f0a1.png">

报了这个错？

**Comment by WittBulter** [comment]
cnpm install jquery 
这个是没找到jquery

**Comment by Bogon** [comment]
恩呢，已经解决了，谢谢。
![ca a lspy d h z0u11b 7s](https://cloud.githubusercontent.com/assets/6748372/14487369/bab9a536-0194-11e6-941e-a25fae94ac3a.jpg)
