### ISSUE TITLE
怎么安装？我安装不了

### ISSUE THREAD

**Issue by devilon** [WittBulter/easyFindNumber#6]
怎么安装？我安装不了，我用的是终端，但装不了啊

**Comment by WittBulter** [comment]
提示什么

**Comment by devilon** [comment]
zsh: command not found: npm

**Comment by WittBulter** [comment]
你需要先安装nodejs与npm，具体可以参见node社区相关贴子。

关闭问题。如果有其他与项目相关问题，请再提出issues
